---
title: "ICE analysis"
author: "Thiago Marques, Phil Neff"
date: "7/21/2020"
output: html_document
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE, results='hide'}
library(here)
library(tidyverse)
library(lubridate)

```

```{r data_import, echo=FALSE, message=FALSE, warning=FALSE, results='hide'}

df_facilities <- read_delim(
  here('analyze', 'input', 'facil-list.csv.gz'), 
  delim = "|") 
          
df_encounters <- read_delim(
  here('analyze', 'input', 'encounters.csv.gz'), 
  delim = "|")
    
df_arrests <- read_delim(
  here('analyze', 'input', 'arrests.csv.gz'),
  delim = "|")
  
df_removals <- read_delim(
  here('analyze', 'input', 'removals.csv.gz'),
  delim = "|")

# This should be in input or frozen instead depending on where AOR-county task ultimately lives
aor_counties <- read_delim(
  here('analyze', 'output', 'county_aor.csv'),
  delim = ',')

```

```{r facil_data_setup_and_filter, message=FALSE, warning=FALSE}

# Dropping ORR facilities
df_facilities <- df_facilities %>% 
  filter(type != "ORR")

# Testing that no other facilties are redacted
stopifnot(sum(df_facilities$detloc == 'Redacted') == 0)

# Concatenate facility city and state columns
df_facilities <- df_facilities %>% 
  unite("city", c(city,state), sep = ", ", remove = FALSE, na.rm = FALSE) %>%
  mutate(city = as.factor(city))

# There's probably a nicer way to convert various fields to factor
# Ideally specify field type on import
df_facilities <- df_facilities %>%
  mutate(detloc = as.factor(detloc))

df_facilities <- df_facilities %>%
  mutate(state = as.factor(state))

df_facilities <- df_facilities %>%
  mutate(city = as.factor(city))

df_facilities <- df_facilities %>%
  mutate(zip = as.factor(zip))

df_facilities <- df_facilities %>%
  mutate(aor = as.factor(aor))

df_facilities <- df_facilities %>%
  mutate(type = as.factor(type))

```

```{r enforcement_data_setup}

# This could be moved into a loop

# ARRESTS

df_arrests <- df_arrests %>% 
  filter(!is.na(aor))

df_arrests <- df_arrests %>% 
  separate(apprehension_date, 
           into = c(
             "apprehension_month", 
             "apprehension_day", 
             "apprehension_year"))

df_arrests <- df_arrests %>% 
  mutate(date = as.Date(paste(df_arrests$apprehension_year,
                              df_arrests$apprehension_month,
                              df_arrests$apprehension_day, sep = "-")))

# Converting date to quarter and fiscal year
df_arrests$apprehension_quarter <- 
  quarter(df_arrests$date, with_year = TRUE, fiscal_start = 10)
df_arrests$apprehension_fy <- stringr::str_sub(df_arrests$apprehension_quarter, 1, 4)
df_arrests$apprehension_fy <- as.integer(df_arrests$apprehension_fy)

# ENCOUNTERS

df_encounters <- df_encounters %>% 
  filter(!is.na(aor))

df_encounters <- df_encounters %>% 
  separate(event_date, 
           into = c(
             "event_month", 
             "event_day", 
             "event_year"))

df_encounters <- df_encounters %>% 
  mutate(date = as.Date(paste(df_encounters$event_year,
                              df_encounters$event_month,
                              df_encounters$event_day, sep = "-")))

# Converting date to quarter and fiscal year
df_encounters$event_quarter <- 
  quarter(df_encounters$date, with_year = TRUE, fiscal_start = 10)
df_encounters$event_fy <- stringr::str_sub(df_encounters$event_quarter, 1, 4)
df_encounters$event_fy <- as.integer(df_encounters$event_fy)

# REMOVALS - REMOVAL DATE

df_removals <- df_removals %>% 
  filter(!is.na(aor))

df_removals <- df_removals %>% 
  separate(removal_date, 
           into = c(
             "removal_month", 
             "removal_day", 
             "removal_year"))

df_removals <- df_removals %>% 
  mutate(date = as.Date(paste(df_removals$removal_year,
                              df_removals$removal_month,
                              df_removals$removal_day, sep = "-")))

# Converting date to quarter and fiscal year
df_removals$removal_quarter <- 
  quarter(df_removals$date, with_year = TRUE, fiscal_start = 10)
df_removals$removal_fy <- stringr::str_sub(df_removals$removal_quarter, 1, 4)
df_removals$removal_fy <- as.integer(df_removals$removal_fy)

# REMOVALS - DEPARTED DATE
df_removals <- df_removals %>% 
  separate(departed_date, 
           into = c(
             "departed_month", 
             "departed_day", 
             "departed_year"))

df_removals <- df_removals %>% 
  mutate(date = as.Date(paste(df_removals$departed_year,
                              df_removals$departed_month,
                              df_removals$departed_day, sep = "-")))

# Converting date to quarter and fiscal year
df_removals$departed_quarter <- 
  quarter(df_removals$date, with_year = TRUE, fiscal_start = 10)
df_removals$departed_fy <- stringr::str_sub(df_removals$departed_quarter, 1, 4)
df_removals$departed_fy <- as.integer(df_removals$departed_fy)



```

```{r aggregate_arrests_to_aor, echo=FALSE, results='hide', warning=FALSE, message=FALSE, include=FALSE}
# aggregate arrests to aor
df_aor_arrests <- df_arrests %>%
  group_by(aor, apprehension_fy) %>% 
  summarize(n_arrests = n()) %>%
  ungroup()

# plot arrests levels
  ggplot(df_aor_arrests) + 
    geom_histogram(mapping = aes(x = n_arrests))

# plot arrests by fiscal year across aor
ggplot(data = df_aor_arrests,
       aes(x = apprehension_fy, 
           y = n_arrests, 
           group = aor, 
           color = aor)) + 
  geom_line() +
  xlab("Fiscal Year") +
  ylab("Number of Arrests") +
  theme_bw() + 
  theme(axis.text.x = element_text(angle = 90, size = 8, vjust = .5))
  labs(title="ICE Arrests per Fiscal Year by AOR", caption="*FY2019 data through Aug. 2019")

# plot arrests by fiscal year across aor with facet wrap
ggplot(data = df_aor_arrests,
       aes(x = apprehension_fy, 
           y = n_arrests, 
           group = aor, 
           color = aor)) + 
  geom_line() +
  xlab("Fiscal Year") +
  ylab("Number of Arrests") +
  theme_bw() + 
  facet_wrap(~ aor) + 
  theme(axis.text.x = element_text(angle = 90, size = 8, vjust = .5)) +
  labs(title="ICE Arrests per Fiscal Year by AOR", caption="*FY2019 data through Aug. 2019")
ggsave(here("analyze", "output", "arrests_facet.pdf"))

```

```{r aggregate_encounters_to_aor, echo=FALSE, results='show', warning=FALSE, message=FALSE, include=FALSE}
# aggregate encounters to aor
df_aor_encounters <- df_encounters %>%
  group_by(aor, event_fy) %>% 
  summarize(n_encounters = n()) %>%
  ungroup()

# plot encounters levels
  ggplot(df_aor_encounters) + 
    geom_histogram(mapping = aes(x = n_encounters))

# plot encounters by fiscal year across aor
ggplot(data = df_aor_encounters,
       aes(x = event_fy, 
           y = n_encounters, 
           group = aor, 
           color = aor)) + 
  geom_line() +
  xlab("Fiscal Year") +
  ylab("Number of encounters") +
  theme_bw() + 
  theme(axis.text.x = element_text(angle = 90, size = 8, vjust = .5))
  labs(title="ICE encounters per Fiscal Year by AOR", caption="*FY2019 data through Aug. 2019")

# plot encounters by fiscal year across aor with facet wrap
ggplot(data = df_aor_encounters,
       aes(x = event_fy, 
           y = n_encounters, 
           group = aor, 
           color = aor)) + 
  geom_line() +
  xlab("Fiscal Year") +
  ylab("Number of encounters") +
  theme_bw() + 
  facet_wrap(~ aor) + 
  theme(axis.text.x = element_text(angle = 90, size = 8, vjust = .5)) +
  labs(title="ICE encounters per Fiscal Year by AOR", caption="*FY2019 data through Aug. 2019")
ggsave(here("analyze", "output", "encounters_facet.pdf"))

```

```{r aggregate_removals_to_aor, echo=FALSE, results='show', warning=FALSE, message=FALSE, include=FALSE}
# aggregate removals to aor
df_aor_removals <- df_removals %>%
  group_by(aor, removal_fy) %>% 
  summarize(n_removals = n()) %>%
  ungroup()

# plot removals levels
  ggplot(df_aor_removals) + 
    geom_histogram(mapping = aes(x = n_removals))

# plot removals by fiscal year across aor
ggplot(data = df_aor_removals,
       aes(x = removal_fy, 
           y = n_removals, 
           group = aor, 
           color = aor)) + 
  geom_line() +
  xlab("Fiscal Year") +
  ylab("Number of removals") +
  theme_bw() + 
  theme(axis.text.x = element_text(angle = 90, size = 8, vjust = .5))
  labs(title="ICE removals per Fiscal Year by AOR", caption="*FY2019 data through Aug. 2019")

# plot removals by fiscal year across aor with facet wrap
ggplot(data = df_aor_removals,
       aes(x = removal_fy, 
           y = n_removals, 
           group = aor, 
           color = aor)) + 
  geom_line() +
  xlab("Fiscal Year") +
  ylab("Number of removals") +
  theme_bw() + 
  facet_wrap(~ aor) + 
  theme(axis.text.x = element_text(angle = 90, size = 8, vjust = .5)) +
  labs(title="ICE removals per Fiscal Year by AOR", caption="*FY2019 data through Aug. 2019")
ggsave(here("analyze", "output", "removals_facet.pdf"))

```

```{r aggregate_adp_to_aor, echo=FALSE, message=FALSE, warning=FALSE, include=FALSE, results='hide'}
# aggregate adp to aor
df_aor_adp <- df_facilities %>%
  group_by(aor) %>% 
  summarize_at(vars(ends_with("adp"), -contains("bookin")), sum) %>%
  ungroup() # 24 AORs

df_aor_adp_pivot <- df_aor_adp %>%
  pivot_longer(
    cols = starts_with("fy"),
    names_to = "fiscal_year",
    values_to = "adp",
    values_drop_na = TRUE
  )

df_aor_adp_pivot$fiscal_year <- df_aor_adp_pivot$fiscal_year %>% str_replace_all('[aA-zZ]', '')

df_aor_adp_pivot$fiscal_year <- paste('20', df_aor_adp_pivot$fiscal_year, sep='')

df_aor_adp_pivot$fiscal_year <- as.integer(df_aor_adp_pivot$fiscal_year) 

ggplot(data = df_aor_adp_pivot,
       aes(x = fiscal_year, y = adp, group = aor, color = aor)) + 
  geom_line() +
  xlab("Fiscal Year") +
  ylab("ADP") +
  theme_bw() + 
  facet_wrap(~ aor) + 
  theme(axis.text.x = element_text(angle = 90, size = 8, vjust = .5)) +
  labs(title="AOR Total ADP per Fiscal Year", caption="*Excluding ORR facilities")
ggsave(here("analyze", "output", "adp_facet.pdf"))
```

```{r join_df_aor_enforcement_long, echo=FALSE, message=FALSE, warning=FALSE, results='hide'}
# create empty data frame
df_aor_enforcement_long <- data.frame(fy = integer(),
                 aor = character(), 
                 stringsAsFactors = FALSE)

# join aor-level encounters data
df_aor_enforcement_long <- df_aor_enforcement_long %>% 
  full_join(df_aor_encounters, 
            by = c("aor", 
                   c("fy" = "event_fy"))
            )
# join aor-level arrests data
df_aor_enforcement_long <- df_aor_enforcement_long %>% 
  full_join(df_aor_arrests, 
            by = c("aor", 
                   c("fy" = "apprehension_fy"))
            )
# join aor-level removals data
df_aor_enforcement_long <- df_aor_enforcement_long %>% 
  full_join(df_aor_removals, 
            by = c("aor", 
                   c("fy" = "removal_fy"))
            )

# recode NA values
# These are dropped for now
df_aor_enforcement_long <- df_aor_enforcement_long %>% 
  mutate(aor = replace_na(aor, "UNKNOWN"))
```

```{r join_df_aor_detention_enforcement_long, echo=FALSE, message=FALSE, warning=FALSE, results='hide'}
# create empty data frame
df_aor_adp_enforcement_long <- data.frame(fy = integer(),
                 aor = character(), 
                 stringsAsFactors = FALSE)

# join adp and enforcement data
df_aor_adp_enforcement_long <- df_aor_adp_enforcement_long %>%
  full_join(df_aor_adp_pivot,
            by = c("aor", 
                   c("fy" = "fiscal_year"))
            )
df_aor_adp_enforcement_long <- df_aor_adp_enforcement_long %>%
  full_join(df_aor_enforcement_long,
            by = c("aor", "fy")
            ) %>%
    arrange(aor, fy, adp)


# convert to factor
df_aor_adp_enforcement_long <- df_aor_adp_enforcement_long %>%
  mutate(aor = as.factor(aor), 
         fy = as.factor(fy)
         )
```

```{r add_new_variables_change_1yr, eval=FALSE, echo=FALSE, message=FALSE, warning=FALSE, results='hide'}

# create one-fy change variables in average daily population and enforcement practices
df_aor_adp_enforcement_long <- df_aor_adp_enforcement_long %>% 
  group_by(aor) %>% 
   # levels
  mutate(
    diff_adp = adp - lag(adp),
    diff_n_encounters = n_encounters - lag(n_encounters), 
    diff_n_arrests = n_arrests - lag(n_arrests),
    diff_n_removals = n_removals - lag(n_removals),
    # percents
    pct_diff_adp = (diff_adp / lag(adp) * 100),
    pct_diff_encounters = (diff_n_encounters / lag(n_encounters) * 100),
    pct_diff_arrests = (diff_n_arrests / lag(n_arrests) * 100),
    pct_diff_removals = (diff_n_removals / lag(n_removals) * 100)
    ) %>%
  ungroup()

# plot percent change in adp by fy across aor
df_aor_adp_enforcement_long %>% 
  ggplot(aes(x = fy, y = pct_diff_adp, group = aor, color = aor)) + 
  geom_hline(yintercept=0, alpha=.33) +
  geom_line() +
  xlab("Fiscal Year") +
  ylab("Percent Change in Average Daily Population (ADP)") + 
  ggtitle("Percent Change in Average Daily Population (ADP), 2009-2018") +
  theme_bw() + 
  facet_wrap(~ aor) + 
  theme(axis.text.x = element_text(angle = 90, size = 8, vjust = .5))
ggsave(here("analyze", "output", "adp_over_time.pdf"))

# plot percent change in encounters by fy across aor
df_aor_adp_enforcement_long %>% 
  filter(!is.na(pct_diff_encounters)) %>% 
  ggplot(aes(x = fy, y = pct_diff_encounters, group = aor, color = aor)) + 
  geom_hline(yintercept=0, alpha=.33) +  
  geom_line() +
  xlab("FY") +
  ylab("Percent Change in Encounters") + 
  ggtitle("Percent Change in Encounters, FY2016-FY2019") +
  theme_bw() + 
  facet_wrap(~ aor) + 
  theme(axis.text.x = element_text(angle = 90, size = 8, vjust = .5))
ggsave(here("analyze", "output", "encounters_over_time.pdf"))

# plot percent change in arrests by year across aor
df_aor_adp_enforcement_long %>% 
  filter(!is.na(pct_diff_arrests)) %>% 
  ggplot(aes(x = fy, y = pct_diff_arrests, group = aor, color = aor)) + 
  geom_hline(yintercept=0, alpha=.33) +  
  geom_line() +
  xlab("FY") +
  ylab("Percent Change in Arrests") + 
  ggtitle("Percent Change in Arrests, FY2016-FY2019") +
  theme_bw() + 
  facet_wrap(~ aor) +
  theme(axis.text.x = element_text(angle = 90, size = 8, vjust = .5))
ggsave(here("analyze", "output", "arrests_over_time.pdf"))

# plot percent change in removals by year across aor
df_aor_adp_enforcement_long %>%
  filter(!is.na(pct_diff_removals)) %>% 
  ggplot(aes(x = fy, y = pct_diff_removals, group = aor, color = aor)) + 
  geom_hline(yintercept=0, alpha=.33) +  
  geom_line() +
  xlab("FY") +
  ylab("Percent Change in Removals") + 
  ggtitle("Percent Change in Removals, FY2016-FY2019") +
  theme_bw() + 
  facet_wrap(~ aor) +
  theme(axis.text.x = element_text(angle = 90, size = 8, vjust = .5))
ggsave(here("analyze", "output", "removals_over_time.pdf"))

```
