---
title: "AOR-weighted"
author: "UWCHR"
date: "1/15/2021"
output: html_document
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE, results='hide'}
library(tidyverse)
library(here)
library(lubridate)
library(skimr)
library(tigris)
library(sf)
library(yaml)
library(here)
library(assertr)
library(ggrepel)
```

```{r load_files, echo=FALSE, message=FALSE, warning=FALSE, results='hide'}

arrests <- read_delim(
  here::here('analyze', 'input', 'arrests.csv.gz'), 
  delim = "|") 

encounters <- read_delim(
  here::here('analyze', 'input', 'encounters.csv.gz'), 
  delim = "|") 

removals <- read_delim(
  here::here('analyze', 'input', 'removals.csv.gz'), 
  delim = "|") 

facilities <- read_delim(
  here::here('analyze', 'input', 'facil-list.csv.gz'), 
  delim = "|") 

dmcp <- read_delim(
  here::here('analyze', 'input', 'dmcp-detailed.csv.gz'), 
  delim = "|") 

county_aor <- read_delim(
  here::here('analyze', 'output', 'county_aor.csv'), 
  delim = ",")

```


```{r facil_data_setup_and_filter, echo=FALSE, message=FALSE, warning=FALSE}

# Dropping ORR facilities
# facilities <- facilities %>% 
  # filter(type != "ORR")

dmcp <- dmcp %>%
  mutate(state = as.factor(state))

dmcp <- dmcp %>%
  mutate(aor = as.factor(aor))

dmcp$over_under_72 <- as.factor(dmcp$over_under_72)

dmcp <- dmcp %>% 
  filter(over_under_72 == "Over 72")

dmcp_as_needed <- dmcp %>% 
  filter(capacity == "AS NEEDED")

facilities <- facilities %>% 
  filter(detloc %in% dmcp$detloc)

# Testing that no other facilties are redacted
stopifnot(sum(facilities$detloc == 'Redacted') == 0)

# Concatenate facility city and state columns
facilities <- facilities %>% 
  unite("city", c(city,state), sep = ", ", remove = FALSE, na.rm = FALSE) %>%
  mutate(city = as.factor(city))

# There's probably a nicer way to convert various fields to factor
# Ideally specify field type on import
facilities <- facilities %>%
  mutate(detloc = as.factor(detloc))

facilities <- facilities %>%
  mutate(state = as.factor(state))

facilities <- facilities %>%
  mutate(city = as.factor(city))

facilities <- facilities %>%
  mutate(zip = as.factor(zip))

facilities <- facilities %>%
  mutate(aor = as.factor(aor))

facilities <- facilities %>%
  mutate(type = as.factor(type))

```


```{r enforcement_data_setup, echo=FALSE, message=FALSE, warning=FALSE}

# This could be moved into a loop

# ARRESTS

#Drop missing aor

predrop <- nrow(arrests) 

arrests <- arrests %>% 
  filter(!is.na(aor))

arrestmissingaor <- predrop - nrow(arrests)
#3,808 missing aor

arrests <- arrests %>% 
  separate(apprehension_date, 
           into = c(
             "apprehension_month", 
             "apprehension_day", 
             "apprehension_year"))

arrests <- arrests %>% 
  mutate(date = as.Date(paste(arrests$apprehension_year,
                              arrests$apprehension_month,
                              arrests$apprehension_day, sep = "-")))

# Converting date to quarter and fiscal year
arrests$apprehension_quarter <- 
  quarter(arrests$date, with_year = TRUE, fiscal_start = 10)
arrests$apprehension_fy <- stringr::str_sub(arrests$apprehension_quarter, 1, 4)
arrests$apprehension_fy <- as.integer(arrests$apprehension_fy)

# ENCOUNTERS

encounters <- encounters %>% 
  filter(!is.na(aor))

encounters <- encounters %>% 
  separate(event_date, 
           into = c(
             "event_month", 
             "event_day", 
             "event_year"))

encounters <- encounters %>% 
  mutate(date = as.Date(paste(encounters$event_year,
                              encounters$event_month,
                              encounters$event_day, sep = "-")))

# Converting date to quarter and fiscal year
encounters$event_quarter <- 
  quarter(encounters$date, with_year = TRUE, fiscal_start = 10)
encounters$event_fy <- stringr::str_sub(encounters$event_quarter, 1, 4)
encounters$event_fy <- as.integer(encounters$event_fy)

# REMOVALS - REMOVAL DATE

removals <- removals %>% 
  filter(!is.na(aor))

removals <- removals %>% 
  separate(removal_date, 
           into = c(
             "removal_month", 
             "removal_day", 
             "removal_year"))

removals <- removals %>% 
  mutate(date = as.Date(paste(removals$removal_year,
                              removals$removal_month,
                              removals$removal_day, sep = "-")))

# Converting date to quarter and fiscal year
removals$removal_quarter <- 
  quarter(removals$date, with_year = TRUE, fiscal_start = 10)
removals$removal_fy <- stringr::str_sub(removals$removal_quarter, 1, 4)
removals$removal_fy <- as.integer(removals$removal_fy)

# REMOVALS - DEPARTED DATE
removals <- removals %>% 
  separate(departed_date, 
           into = c(
             "departed_month", 
             "departed_day", 
             "departed_year"))

removals <- removals %>% 
  mutate(date = as.Date(paste(removals$departed_year,
                              removals$departed_month,
                              removals$departed_day, sep = "-")))

# Converting date to quarter and fiscal year
removals$departed_quarter <- 
  quarter(removals$date, with_year = TRUE, fiscal_start = 10)
removals$departed_fy <- stringr::str_sub(removals$departed_quarter, 1, 4)
removals$departed_fy <- as.integer(removals$departed_fy)



```


``` {r group_arrests, echo=FALSE, message=FALSE, warning=FALSE}

# group arrests by aor
aor_arrests <- arrests %>%
  group_by(aor, apprehension_fy) %>% 
  summarize(n_arrests = n()) %>% 
  rename(
    fy = apprehension_fy
  )

# group encounters by aor
aor_encounters <- encounters %>%
  group_by(aor, event_fy) %>% 
  summarize(n_encounters = n()) %>% 
  rename(
    fy = event_fy
  )

# group removals by aor
aor_removals <- removals %>%
  group_by(aor, departed_fy) %>% 
  summarize(n_removals = n()) %>% 
  rename(
    fy = departed_fy
  )

# group county pop by aor
aor_pop <- county_aor %>% 
  group_by(aor) %>% 
  summarize(population = sum(estimate))

# group adp by aor
aor_adp <- facilities %>%
  group_by(aor) %>% 
  summarize_at(vars(ends_with("adp"), -contains("bookin")), sum) %>%
  ungroup() # 24 AORs

aor_adp <- aor_adp %>%
  pivot_longer(
    cols = starts_with("fy"),
    names_to = "fy",
    values_to = "adp",
    values_drop_na = TRUE
  )

aor_adp$fy <- aor_adp$fy %>% str_replace_all('[aA-zZ]', '')
aor_adp$fy <- paste('20', aor_adp$fy, sep='')
aor_adp$fy <- as.integer(aor_adp$fy) 

aor_enforce_adp <- merge(aor_arrests, aor_adp, by=c('aor', 'fy'))

aor_enforce_adp <- merge(aor_enforce_adp, aor_encounters, by=c('aor', 'fy'))

aor_enforce_adp <- merge(aor_enforce_adp, aor_removals, by=c('aor', 'fy'))

aor_enforce_adp <- merge(aor_enforce_adp, aor_pop, by='aor')

aor_enforce_adp$adp_per_capita = aor_enforce_adp$adp / aor_enforce_adp$population
aor_enforce_adp$arrests_per_capita = aor_enforce_adp$n_arrests / aor_enforce_adp$population
aor_enforce_adp$encounters_per_capita = aor_enforce_adp$n_encounters / aor_enforce_adp$population
aor_enforce_adp$removals_per_capita = aor_enforce_adp$n_removals / aor_enforce_adp$population


```

```{r plot_arrests_adp_per_capita, echo=FALSE, message=FALSE, warning=FALSE}

# This might be a better labelling solution but doesn't use ggplot
# https://europebynumbers.wordpress.com/2019/11/21/how-to-label-points-on-a-scatterplot-with-r-for-lattice/
# require(devtools)
# devtools::install_github("https://github.com/m-jahn/lattice-tools")
# library(latticetools)

p <- aor_enforce_adp %>% 
  ggplot(aes(
    x = log(adp_per_capita),
    y = log(arrests_per_capita), colour=aor, label=aor)) +
  geom_point()

directlabels::direct.label(p, 'extreme.points')

library('lattice')
library('latticetools')

xyplot(arrests_per_capita ~ adp_per_capita, aor_enforce_adp,
       groups = aor,
       labels = aor_enforce_adp$aor, cex = 0.75,
       panel = function(x, y, ...) {
    panel.grid(h = -1, v = -1, col.line = grey(0.9))
    panel.xyplot(x, y, ...)
    panel.directlabel(x, y,
      # y_boundary = c(.0010, 10),
      x_boundary = c(.0002, 10),
      draw_box = TRUE, box_line = TRUE, ...)
  }
)

```

```{r plot_arrests_adp_per_capita_simple, echo=FALSE, message=FALSE, warning=FALSE}

p <- aor_enforce_adp %>% 
  ggplot(aes(x = adp_per_capita, y = arrests_per_capita, colour=aor, label=aor)) +
  geom_point()

directlabels::direct.label(p, 'extreme.points')


```

```{r plot_encounters_adp_per_capita_simple, echo=FALSE, message=FALSE, warning=FALSE}

p <- aor_enforce_adp %>% 
  ggplot(aes(x = adp_per_capita, y = encounters_per_capita, colour=aor, label=aor)) +
  geom_point()

directlabels::direct.label(p, 'extreme.points')

```

```{r plot_removals_adp_per_capita_simple, echo=FALSE, message=FALSE, warning=FALSE}

p <- aor_enforce_adp %>% 
  ggplot(aes(x = adp_per_capita, y = removals_per_capita, colour=aor, label=aor)) +
  geom_point()

directlabels::direct.label(p, 'extreme.points')

```

```{r plot_removals_arrests_per_capita_simple, echo=FALSE, message=FALSE, warning=FALSE}

p <- aor_enforce_adp %>% 
  ggplot(aes(x = arrests_per_capita, y = removals_per_capita, colour=aor, label=aor)) +
  geom_point()

directlabels::direct.label(p, 'extreme.points')

```

```{r plot_encounters_arrests_per_capita_simple, echo=FALSE, message=FALSE, warning=FALSE}

p <- aor_enforce_adp %>% 
  ggplot(aes(x = arrests_per_capita, y = encounters_per_capita, colour=aor, label=aor)) +
  geom_point()

directlabels::direct.label(p, 'extreme.points')

```

```{r removal_adp_lm}

model1 <- lm(removals_per_capita ~ adp_per_capita, data = aor_enforce_adp)


summary(model1)
print(model1$coefficients)

```

```{r arrests_adp_lm}

model1 <- lm(arrests_per_capita ~ adp_per_capita, data = aor_enforce_adp)


summary(model1)
print(model1$coefficients)

```

```{r encounters_adp_lm}

model1 <- lm(encounters_per_capita ~ adp_per_capita, data = aor_enforce_adp)


summary(model1)
print(model1$coefficients)

```
