---
title: "Merging datasets of old and new detention facilities"
author: "Trung-Anh Nguyen"
date: "10/11/2021"
output: html_document
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
#remove(list = ls())
```

## Add and clean datasets



```{r}
facilities <- read.csv("../input/facil-list.csv.gz", sep = "|")
dmcp <- read.csv("../input/dmcp-detailed.csv.gz", sep = "|")
new_facilities <- read.csv("../hand/to_research.csv")

facilities_clean <- facilities %>% select(1:12)
new_facilities_clean <- new_facilities %>% select(1:7) %>%
  rename(detloc = detention_facility_code,
         name = detention_facility,
         type = contract) %>%
  filter(rec_count >= 50) %>%
  mutate(over_72 = case_when(over_72 == "Y" ~ TRUE,
                             TRUE ~ FALSE))
dmcp_clean <- dmcp %>% select(detloc, over_under_72) %>%
  mutate(over_72 = case_when(over_under_72 == "Over 72" ~ TRUE,
                             TRUE ~ FALSE)) %>%
  select(-over_under_72)
```

## Joining


```{r}
facilities_clean <- merge(facilities_clean, dmcp_clean, by = "detloc")
facilities_both <- bind_rows(facilities_clean, new_facilities_clean)
write.csv(facilities_both, "../output/facilities.csv")
```

